apiVersion: v1
kind: Service
metadata:
  name: myqrlwallet-frontend
  namespace: myqrlwallet
  labels:
    app: myqrlwallet-frontend
    app.kubernetes.io/name: myqrlwallet-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: myqrlwallet
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: myqrlwallet-frontend
